name: dnd_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  get: ^4.6.5
  flutter_bloc: ^8.1.2
  flutter_native_splash: ^2.3.0
  http: ^0.13.5
  shared_preferences: ^2.1.1
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.2.3
  flutter_statusbarcolor_ns: ^0.5.0
  flutter_staggered_animations: ^1.1.1
  animated_bottom_navigation_bar: ^1.2.0

flutter_native_splash:
  image: "lib/assets/images/img_dnd_splash.jpg"
  android: true
  ios: true
  web: false
  color: "#000000"
  android_12:
    color: "#000000"


flutter_icons:
  image_path_android: 'lib/assets/images/dnd_icon_android.png'
  adaptive_icon_foreground: 'lib/assets/images/dnd_icon_android.png'
  image_path_ios: 'lib/assets/images/dnd_icon.jpeg'
  adaptive_icon_background: "#000000"
  android: true
  ios: true
  min_sdk_android: 21
  remove_alpha_ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - lib/assets/images/

